# CONSTANTS
GENOME_SIZE = 8 # N-QUEENS (EX: 'every Queen has a genome size of 8')
POPULATION_SIZE = 100
NUM_OFFSPRING = 2
RECOMBINATION_RATE = 0.70  
MUTATION_RATE = 0.8
MAX_FITNESS_EVALUATIONS = 10000