setup17 = {
    'GENOME_SIZE': 8,
    'MAX_FITNESS_EVALUATIONS': 10000,
    'fitness_strategy': 'conflict_based',
    'termination_strategy': 'evaluation_count',
    'visualization_strategy': 'terminal',
    'metric_strategy': 'avg_similarity',
    'logging_strategy': 'logger',
    'print_type': 'csv_file',
    'POPULATION_SIZE': 101,
    'NUM_OFFSPRING_RATE': 0.53,
    'RECOMBINATION_RATE': 0.624,
    'MUTATION_RATE': 0.259,
    'TOURNAMENT_GROUP_SIZE': 0.513,
    'initialization_strategy': 'random',
    'parent_selection_strategy': 'tournament',
    'recombination_strategy': 'ordered_crossover',
    'mutation_strategy': 'creep_mutation',
    'survival_selection_strategy': 'prob_survival',
}

setup74 = {
    'GENOME_SIZE': 8,
    'MAX_FITNESS_EVALUATIONS': 10000,
    'fitness_strategy': 'conflict_based',
    'termination_strategy': 'evaluation_count',
    'visualization_strategy': 'terminal',
    'metric_strategy': 'avg_similarity',
    'logging_strategy': 'logger',
    'print_type': 'csv_file',
    'POPULATION_SIZE': 99,
    'NUM_OFFSPRING_RATE': 0.696,
    'RECOMBINATION_RATE': 0.825,
    'MUTATION_RATE': 0.139,
    'TOURNAMENT_GROUP_SIZE': 0.338,
    'initialization_strategy': 'random',
    'parent_selection_strategy': 'tournament',
    'recombination_strategy': 'ordered_crossover',
    'mutation_strategy': 'creep_mutation',
    'survival_selection_strategy': 'prob_survival',
}

setup6 = {
    'GENOME_SIZE': 8,
    'MAX_FITNESS_EVALUATIONS': 10000,
    'fitness_strategy': 'conflict_based',
    'termination_strategy': 'evaluation_count',
    'visualization_strategy': 'terminal',
    'metric_strategy': 'avg_similarity',
    'logging_strategy': 'logger',
    'print_type': 'csv_file',
    'POPULATION_SIZE': 100,
    'NUM_OFFSPRING_RATE': 0.431,
    'RECOMBINATION_RATE': 0.645,
    'MUTATION_RATE': 0.207,
    'TOURNAMENT_GROUP_SIZE': 0.396,
    'initialization_strategy': 'random',
    'parent_selection_strategy': 'tournament',
    'recombination_strategy': 'ordered_crossover',
    'mutation_strategy': 'creep_mutation',
    'survival_selection_strategy': 'prob_survival',
}

setup76 = {
    'GENOME_SIZE': 8,
    'MAX_FITNESS_EVALUATIONS': 10000,
    'fitness_strategy': 'conflict_based',
    'termination_strategy': 'evaluation_count',
    'visualization_strategy': 'terminal',
    'metric_strategy': 'avg_similarity',
    'logging_strategy': 'logger',
    'print_type': 'csv_file',
    'POPULATION_SIZE': 99,
    'NUM_OFFSPRING_RATE': 0.356,
    'RECOMBINATION_RATE': 0.738,
    'MUTATION_RATE': 0.158,
    'TOURNAMENT_GROUP_SIZE': 0.596,
    'initialization_strategy': 'random',
    'parent_selection_strategy': 'tournament',
    'recombination_strategy': 'ordered_crossover',
    'mutation_strategy': 'creep_mutation',
    'survival_selection_strategy': 'prob_survival',
}

setup97 = {
    'GENOME_SIZE': 8,
    'MAX_FITNESS_EVALUATIONS': 10000,
    'fitness_strategy': 'conflict_based',
    'termination_strategy': 'evaluation_count',
    'visualization_strategy': 'terminal',
    'metric_strategy': 'avg_similarity',
    'logging_strategy': 'logger',
    'print_type': 'csv_file',
    'POPULATION_SIZE': 101,
    'NUM_OFFSPRING_RATE': 0.68,
    'RECOMBINATION_RATE': 0.694,
    'MUTATION_RATE': 0.248,
    'TOURNAMENT_GROUP_SIZE': 0.335,
    'initialization_strategy': 'random',
    'parent_selection_strategy': 'tournament',
    'recombination_strategy': 'ordered_crossover',
    'mutation_strategy': 'creep_mutation',
    'survival_selection_strategy': 'prob_survival',
}

setup58 = {
    'GENOME_SIZE': 8,
    'MAX_FITNESS_EVALUATIONS': 10000,
    'fitness_strategy': 'conflict_based',
    'termination_strategy': 'evaluation_count',
    'visualization_strategy': 'terminal',
    'metric_strategy': 'avg_similarity',
    'logging_strategy': 'logger',
    'print_type': 'csv_file',
    'POPULATION_SIZE': 100,
    'NUM_OFFSPRING_RATE': 0.328,
    'RECOMBINATION_RATE': 0.635,
    'MUTATION_RATE': 0.087,
    'TOURNAMENT_GROUP_SIZE': 0.328,
    'initialization_strategy': 'random',
    'parent_selection_strategy': 'tournament',
    'recombination_strategy': 'ordered_crossover',
    'mutation_strategy': 'creep_mutation',
    'survival_selection_strategy': 'prob_survival',
}

setup87 = {
    'GENOME_SIZE': 8,
    'MAX_FITNESS_EVALUATIONS': 10000,
    'fitness_strategy': 'conflict_based',
    'termination_strategy': 'evaluation_count',
    'visualization_strategy': 'terminal',
    'metric_strategy': 'avg_similarity',
    'logging_strategy': 'logger',
    'print_type': 'csv_file',
    'POPULATION_SIZE': 99,
    'NUM_OFFSPRING_RATE': 0.58,
    'RECOMBINATION_RATE': 0.794,
    'MUTATION_RATE': 0.073,
    'TOURNAMENT_GROUP_SIZE': 0.472,
    'initialization_strategy': 'random',
    'parent_selection_strategy': 'tournament',
    'recombination_strategy': 'ordered_crossover',
    'mutation_strategy': 'creep_mutation',
    'survival_selection_strategy': 'prob_survival',
}

setup31 = {
    'GENOME_SIZE': 8,
    'MAX_FITNESS_EVALUATIONS': 10000,
    'fitness_strategy': 'conflict_based',
    'termination_strategy': 'evaluation_count',
    'visualization_strategy': 'terminal',
    'metric_strategy': 'avg_similarity',
    'logging_strategy': 'logger',
    'print_type': 'csv_file',
    'POPULATION_SIZE': 101,
    'NUM_OFFSPRING_RATE': 0.618,
    'RECOMBINATION_RATE': 0.714,
    'MUTATION_RATE': 0.263,
    'TOURNAMENT_GROUP_SIZE': 0.525,
    'initialization_strategy': 'random',
    'parent_selection_strategy': 'tournament',
    'recombination_strategy': 'ordered_crossover',
    'mutation_strategy': 'creep_mutation',
    'survival_selection_strategy': 'prob_survival',
}

setup32 = {
    'GENOME_SIZE': 8,
    'MAX_FITNESS_EVALUATIONS': 10000,
    'fitness_strategy': 'conflict_based',
    'termination_strategy': 'evaluation_count',
    'visualization_strategy': 'terminal',
    'metric_strategy': 'avg_similarity',
    'logging_strategy': 'logger',
    'print_type': 'csv_file',
    'POPULATION_SIZE': 100,
    'NUM_OFFSPRING_RATE': 0.449,
    'RECOMBINATION_RATE': 0.803,
    'MUTATION_RATE': 0.24,
    'TOURNAMENT_GROUP_SIZE': 0.31,
    'initialization_strategy': 'random',
    'parent_selection_strategy': 'tournament',
    'recombination_strategy': 'ordered_crossover',
    'mutation_strategy': 'creep_mutation',
    'survival_selection_strategy': 'prob_survival',
}

setup3 = {
    'GENOME_SIZE': 8,
    'MAX_FITNESS_EVALUATIONS': 10000,
    'fitness_strategy': 'conflict_based',
    'termination_strategy': 'evaluation_count',
    'visualization_strategy': 'terminal',
    'metric_strategy': 'avg_similarity',
    'logging_strategy': 'logger',
    'print_type': 'csv_file',
    'POPULATION_SIZE': 100,
    'NUM_OFFSPRING_RATE': 0.381,
    'RECOMBINATION_RATE': 0.681,
    'MUTATION_RATE': 0.199,
    'TOURNAMENT_GROUP_SIZE': 0.325,
    'initialization_strategy': 'random',
    'parent_selection_strategy': 'tournament',
    'recombination_strategy': 'ordered_crossover',
    'mutation_strategy': 'scramble_mutation',
    'survival_selection_strategy': 'prob_survival',
}

setup61 = {
    'GENOME_SIZE': 8,
    'MAX_FITNESS_EVALUATIONS': 10000,
    'fitness_strategy': 'conflict_based',
    'termination_strategy': 'evaluation_count',
    'visualization_strategy': 'terminal',
    'metric_strategy': 'avg_similarity',
    'logging_strategy': 'logger',
    'print_type': 'csv_file',
    'POPULATION_SIZE': 101,
    'NUM_OFFSPRING_RATE': 0.715,
    'RECOMBINATION_RATE': 0.669,
    'MUTATION_RATE': 0.117,
    'TOURNAMENT_GROUP_SIZE': 0.535,
    'initialization_strategy': 'random',
    'parent_selection_strategy': 'tournament',
    'recombination_strategy': 'ordered_crossover',
    'mutation_strategy': 'creep_mutation',
    'survival_selection_strategy': 'prob_survival',
}

setup70 = {
    'GENOME_SIZE': 8,
    'MAX_FITNESS_EVALUATIONS': 10000,
    'fitness_strategy': 'conflict_based',
    'termination_strategy': 'evaluation_count',
    'visualization_strategy': 'terminal',
    'metric_strategy': 'avg_similarity',
    'logging_strategy': 'logger',
    'print_type': 'csv_file',
    'POPULATION_SIZE': 99,
    'NUM_OFFSPRING_RATE': 0.427,
    'RECOMBINATION_RATE': 0.668,
    'MUTATION_RATE': 0.274,
    'TOURNAMENT_GROUP_SIZE': 0.383,
    'initialization_strategy': 'random',
    'parent_selection_strategy': 'tournament',
    'recombination_strategy': 'ordered_crossover',
    'mutation_strategy': 'scramble_mutation',
    'survival_selection_strategy': 'prob_survival',
}

setup5 = {
    'GENOME_SIZE': 8,
    'MAX_FITNESS_EVALUATIONS': 10000,
    'fitness_strategy': 'conflict_based',
    'termination_strategy': 'evaluation_count',
    'visualization_strategy': 'terminal',
    'metric_strategy': 'avg_similarity',
    'logging_strategy': 'logger',
    'print_type': 'csv_file',
    'POPULATION_SIZE': 101,
    'NUM_OFFSPRING_RATE': 0.387,
    'RECOMBINATION_RATE': 0.891,
    'MUTATION_RATE': 0.174,
    'TOURNAMENT_GROUP_SIZE': 0.503,
    'initialization_strategy': 'random',
    'parent_selection_strategy': 'tournament',
    'recombination_strategy': 'ordered_crossover',
    'mutation_strategy': 'creep_mutation',
    'survival_selection_strategy': 'prob_survival',
}

setup35 = {
    'GENOME_SIZE': 8,
    'MAX_FITNESS_EVALUATIONS': 10000,
    'fitness_strategy': 'conflict_based',
    'termination_strategy': 'evaluation_count',
    'visualization_strategy': 'terminal',
    'metric_strategy': 'avg_similarity',
    'logging_strategy': 'logger',
    'print_type': 'csv_file',
    'POPULATION_SIZE': 100,
    'NUM_OFFSPRING_RATE': 0.369,
    'RECOMBINATION_RATE': 0.752,
    'MUTATION_RATE': 0.221,
    'TOURNAMENT_GROUP_SIZE': 0.553,
    'initialization_strategy': 'random',
    'parent_selection_strategy': 'tournament',
    'recombination_strategy': 'ordered_crossover',
    'mutation_strategy': 'creep_mutation',
    'survival_selection_strategy': 'prob_survival',
}

setup75 = {
    'GENOME_SIZE': 8,
    'MAX_FITNESS_EVALUATIONS': 10000,
    'fitness_strategy': 'conflict_based',
    'termination_strategy': 'evaluation_count',
    'visualization_strategy': 'terminal',
    'metric_strategy': 'avg_similarity',
    'logging_strategy': 'logger',
    'print_type': 'csv_file',
    'POPULATION_SIZE': 100,
    'NUM_OFFSPRING_RATE': 0.652,
    'RECOMBINATION_RATE': 0.836,
    'MUTATION_RATE': 0.036,
    'TOURNAMENT_GROUP_SIZE': 0.424,
    'initialization_strategy': 'random',
    'parent_selection_strategy': 'tournament',
    'recombination_strategy': 'ordered_crossover',
    'mutation_strategy': 'scramble_mutation',
    'survival_selection_strategy': 'prob_survival',
}

