setup47 = {
    'GENOME_SIZE': 8,
    'MAX_FITNESS_EVALUATIONS': 10000,
    'fitness_strategy': 'conflict_based',
    'termination_strategy': 'evaluation_count',
    'visualization_strategy': 'terminal',
    'metric_strategy': 'avg_similarity',
    'logging_strategy': 'logger',
    'print_type': 'csv_file',
    'POPULATION_SIZE': 188,
    'NUM_OFFSPRING_RATE': 0.22,
    'RECOMBINATION_RATE': 0.886,
    'MUTATION_RATE': 0.433,
    'TOURNAMENT_GROUP_SIZE': 0.558,
    'initialization_strategy': 'random_permutations',
    'parent_selection_strategy': 'tournament',
    'recombination_strategy': 'pmx_dp_rm',
    'mutation_strategy': 'duplicate_replacement',
    'survival_selection_strategy': 'prob_survival',
}

setup8 = {
    'GENOME_SIZE': 8,
    'MAX_FITNESS_EVALUATIONS': 10000,
    'fitness_strategy': 'conflict_based',
    'termination_strategy': 'evaluation_count',
    'visualization_strategy': 'terminal',
    'metric_strategy': 'avg_similarity',
    'logging_strategy': 'logger',
    'print_type': 'csv_file',
    'POPULATION_SIZE': 69,
    'NUM_OFFSPRING_RATE': 0.407,
    'RECOMBINATION_RATE': 0.898,
    'MUTATION_RATE': 0.273,
    'TOURNAMENT_GROUP_SIZE': 0.686,
    'initialization_strategy': 'random_permutations',
    'parent_selection_strategy': 'tournament',
    'recombination_strategy': 'pmx_dp_rm',
    'mutation_strategy': 'swap_mutation',
    'survival_selection_strategy': 'prob_survival',
}

setup29 = {
    'GENOME_SIZE': 8,
    'MAX_FITNESS_EVALUATIONS': 10000,
    'fitness_strategy': 'conflict_based',
    'termination_strategy': 'evaluation_count',
    'visualization_strategy': 'terminal',
    'metric_strategy': 'avg_similarity',
    'logging_strategy': 'logger',
    'print_type': 'csv_file',
    'POPULATION_SIZE': 131,
    'NUM_OFFSPRING_RATE': 0.471,
    'RECOMBINATION_RATE': 0.774,
    'MUTATION_RATE': 0.247,
    'TOURNAMENT_GROUP_SIZE': 0.543,
    'initialization_strategy': 'random_permutations',
    'parent_selection_strategy': 'tournament',
    'recombination_strategy': 'partially_mapped_crossover',
    'mutation_strategy': 'duplicate_replacement',
    'survival_selection_strategy': 'prob_survival',
}

setup83 = {
    'GENOME_SIZE': 8,
    'MAX_FITNESS_EVALUATIONS': 10000,
    'fitness_strategy': 'conflict_based',
    'termination_strategy': 'evaluation_count',
    'visualization_strategy': 'terminal',
    'metric_strategy': 'avg_similarity',
    'logging_strategy': 'logger',
    'print_type': 'csv_file',
    'POPULATION_SIZE': 61,
    'NUM_OFFSPRING_RATE': 0.312,
    'RECOMBINATION_RATE': 0.743,
    'MUTATION_RATE': 0.304,
    'TOURNAMENT_GROUP_SIZE': 0.164,
    'initialization_strategy': 'random_permutations',
    'parent_selection_strategy': 'tournament',
    'recombination_strategy': 'pmx_dp_rm',
    'mutation_strategy': 'inversion_mutation',
    'survival_selection_strategy': 'prob_survival',
}

setup49 = {
    'GENOME_SIZE': 8,
    'MAX_FITNESS_EVALUATIONS': 10000,
    'fitness_strategy': 'conflict_based',
    'termination_strategy': 'evaluation_count',
    'visualization_strategy': 'terminal',
    'metric_strategy': 'avg_similarity',
    'logging_strategy': 'logger',
    'print_type': 'csv_file',
    'POPULATION_SIZE': 66,
    'NUM_OFFSPRING_RATE': 0.411,
    'RECOMBINATION_RATE': 0.7,
    'MUTATION_RATE': 0.293,
    'TOURNAMENT_GROUP_SIZE': 0.647,
    'initialization_strategy': 'random_permutations',
    'parent_selection_strategy': 'tournament',
    'recombination_strategy': 'partially_mapped_crossover',
    'mutation_strategy': 'inversion_mutation',
    'survival_selection_strategy': 'prob_survival',
}

setup88 = {
    'GENOME_SIZE': 8,
    'MAX_FITNESS_EVALUATIONS': 10000,
    'fitness_strategy': 'conflict_based',
    'termination_strategy': 'evaluation_count',
    'visualization_strategy': 'terminal',
    'metric_strategy': 'avg_similarity',
    'logging_strategy': 'logger',
    'print_type': 'csv_file',
    'POPULATION_SIZE': 67,
    'NUM_OFFSPRING_RATE': 0.365,
    'RECOMBINATION_RATE': 0.862,
    'MUTATION_RATE': 0.359,
    'TOURNAMENT_GROUP_SIZE': 0.432,
    'initialization_strategy': 'random_permutations',
    'parent_selection_strategy': 'tournament',
    'recombination_strategy': 'partially_mapped_crossover',
    'mutation_strategy': 'inversion_mutation',
    'survival_selection_strategy': 'prob_survival',
}

setup23 = {
    'GENOME_SIZE': 8,
    'MAX_FITNESS_EVALUATIONS': 10000,
    'fitness_strategy': 'conflict_based',
    'termination_strategy': 'evaluation_count',
    'visualization_strategy': 'terminal',
    'metric_strategy': 'avg_similarity',
    'logging_strategy': 'logger',
    'print_type': 'csv_file',
    'POPULATION_SIZE': 108,
    'NUM_OFFSPRING_RATE': 0.434,
    'RECOMBINATION_RATE': 0.601,
    'MUTATION_RATE': 0.259,
    'TOURNAMENT_GROUP_SIZE': 0.218,
    'initialization_strategy': 'random_permutations',
    'parent_selection_strategy': 'tournament',
    'recombination_strategy': 'pmx_dp_rm',
    'mutation_strategy': 'swap_mutation',
    'survival_selection_strategy': 'prob_survival',
}

setup64 = {
    'GENOME_SIZE': 8,
    'MAX_FITNESS_EVALUATIONS': 10000,
    'fitness_strategy': 'conflict_based',
    'termination_strategy': 'evaluation_count',
    'visualization_strategy': 'terminal',
    'metric_strategy': 'avg_similarity',
    'logging_strategy': 'logger',
    'print_type': 'csv_file',
    'POPULATION_SIZE': 160,
    'NUM_OFFSPRING_RATE': 0.428,
    'RECOMBINATION_RATE': 0.674,
    'MUTATION_RATE': 0.488,
    'TOURNAMENT_GROUP_SIZE': 0.722,
    'initialization_strategy': 'random_permutations',
    'parent_selection_strategy': 'tournament',
    'recombination_strategy': 'partially_mapped_crossover',
    'mutation_strategy': 'duplicate_replacement',
    'survival_selection_strategy': 'prob_survival',
}

setup71 = {
    'GENOME_SIZE': 8,
    'MAX_FITNESS_EVALUATIONS': 10000,
    'fitness_strategy': 'conflict_based',
    'termination_strategy': 'evaluation_count',
    'visualization_strategy': 'terminal',
    'metric_strategy': 'avg_similarity',
    'logging_strategy': 'logger',
    'print_type': 'csv_file',
    'POPULATION_SIZE': 132,
    'NUM_OFFSPRING_RATE': 0.19,
    'RECOMBINATION_RATE': 0.755,
    'MUTATION_RATE': 0.221,
    'TOURNAMENT_GROUP_SIZE': 0.594,
    'initialization_strategy': 'random_permutations',
    'parent_selection_strategy': 'tournament',
    'recombination_strategy': 'pmx_dp_rm',
    'mutation_strategy': 'swap_mutation',
    'survival_selection_strategy': 'prob_survival',
}

setup14 = {
    'GENOME_SIZE': 8,
    'MAX_FITNESS_EVALUATIONS': 10000,
    'fitness_strategy': 'conflict_based',
    'termination_strategy': 'evaluation_count',
    'visualization_strategy': 'terminal',
    'metric_strategy': 'avg_similarity',
    'logging_strategy': 'logger',
    'print_type': 'csv_file',
    'POPULATION_SIZE': 146,
    'NUM_OFFSPRING_RATE': 0.383,
    'RECOMBINATION_RATE': 0.893,
    'MUTATION_RATE': 0.478,
    'TOURNAMENT_GROUP_SIZE': 0.491,
    'initialization_strategy': 'random_permutations',
    'parent_selection_strategy': 'tournament',
    'recombination_strategy': 'partially_mapped_crossover',
    'mutation_strategy': 'inversion_mutation',
    'survival_selection_strategy': 'prob_survival',
}

