setup69 = {
    'GENOME_SIZE': 8,
    'MAX_FITNESS_EVALUATIONS': 10000,
    'fitness_strategy': 'conflict_based',
    'termination_strategy': 'evaluation_count',
    'visualization_strategy': 'terminal',
    'metric_strategy': 'avg_similarity',
    'logging_strategy': 'logger',
    'print_type': 'csv_file',
    'POPULATION_SIZE': 123,
    'NUM_OFFSPRING_RATE': 0.496,
    'RECOMBINATION_RATE': 0.844,
    'MUTATION_RATE': 0.463,
    'TOURNAMENT_GROUP_SIZE': 0.422,
    'initialization_strategy': 'random_permutations',
    'parent_selection_strategy': 'tournament',
    'recombination_strategy': 'partially_mapped_crossover',
    'mutation_strategy': 'inversion_mutation',
    'survival_selection_strategy': 'prob_survival',
}

setup96 = {
    'GENOME_SIZE': 8,
    'MAX_FITNESS_EVALUATIONS': 10000,
    'fitness_strategy': 'conflict_based',
    'termination_strategy': 'evaluation_count',
    'visualization_strategy': 'terminal',
    'metric_strategy': 'avg_similarity',
    'logging_strategy': 'logger',
    'print_type': 'csv_file',
    'POPULATION_SIZE': 136,
    'NUM_OFFSPRING_RATE': 0.479,
    'RECOMBINATION_RATE': 0.868,
    'MUTATION_RATE': 0.381,
    'TOURNAMENT_GROUP_SIZE': 0.551,
    'initialization_strategy': 'random_permutations',
    'parent_selection_strategy': 'tournament',
    'recombination_strategy': 'partially_mapped_crossover',
    'mutation_strategy': 'swap_mutation',
    'survival_selection_strategy': 'prob_survival',
}

setup2 = {
    'GENOME_SIZE': 8,
    'MAX_FITNESS_EVALUATIONS': 10000,
    'fitness_strategy': 'conflict_based',
    'termination_strategy': 'evaluation_count',
    'visualization_strategy': 'terminal',
    'metric_strategy': 'avg_similarity',
    'logging_strategy': 'logger',
    'print_type': 'csv_file',
    'POPULATION_SIZE': 173,
    'NUM_OFFSPRING_RATE': 0.386,
    'RECOMBINATION_RATE': 0.807,
    'MUTATION_RATE': 0.284,
    'TOURNAMENT_GROUP_SIZE': 0.675,
    'initialization_strategy': 'random_permutations',
    'parent_selection_strategy': 'tournament',
    'recombination_strategy': 'partially_mapped_crossover',
    'mutation_strategy': 'swap_mutation',
    'survival_selection_strategy': 'prob_survival',
}

setup45 = {
    'GENOME_SIZE': 8,
    'MAX_FITNESS_EVALUATIONS': 10000,
    'fitness_strategy': 'conflict_based',
    'termination_strategy': 'evaluation_count',
    'visualization_strategy': 'terminal',
    'metric_strategy': 'avg_similarity',
    'logging_strategy': 'logger',
    'print_type': 'csv_file',
    'POPULATION_SIZE': 154,
    'NUM_OFFSPRING_RATE': 0.399,
    'RECOMBINATION_RATE': 0.811,
    'MUTATION_RATE': 0.107,
    'TOURNAMENT_GROUP_SIZE': 0.369,
    'initialization_strategy': 'random_permutations',
    'parent_selection_strategy': 'tournament',
    'recombination_strategy': 'pmx_dp_rm',
    'mutation_strategy': 'duplicate_replacement',
    'survival_selection_strategy': 'prob_survival',
}

setup56 = {
    'GENOME_SIZE': 8,
    'MAX_FITNESS_EVALUATIONS': 10000,
    'fitness_strategy': 'conflict_based',
    'termination_strategy': 'evaluation_count',
    'visualization_strategy': 'terminal',
    'metric_strategy': 'avg_similarity',
    'logging_strategy': 'logger',
    'print_type': 'csv_file',
    'POPULATION_SIZE': 129,
    'NUM_OFFSPRING_RATE': 0.428,
    'RECOMBINATION_RATE': 0.642,
    'MUTATION_RATE': 0.241,
    'TOURNAMENT_GROUP_SIZE': 0.113,
    'initialization_strategy': 'random_permutations',
    'parent_selection_strategy': 'tournament',
    'recombination_strategy': 'pmx_dp_rm',
    'mutation_strategy': 'swap_mutation',
    'survival_selection_strategy': 'prob_survival',
}

setup58 = {
    'GENOME_SIZE': 8,
    'MAX_FITNESS_EVALUATIONS': 10000,
    'fitness_strategy': 'conflict_based',
    'termination_strategy': 'evaluation_count',
    'visualization_strategy': 'terminal',
    'metric_strategy': 'avg_similarity',
    'logging_strategy': 'logger',
    'print_type': 'csv_file',
    'POPULATION_SIZE': 51,
    'NUM_OFFSPRING_RATE': 0.295,
    'RECOMBINATION_RATE': 0.629,
    'MUTATION_RATE': 0.403,
    'TOURNAMENT_GROUP_SIZE': 0.162,
    'initialization_strategy': 'random_permutations',
    'parent_selection_strategy': 'tournament',
    'recombination_strategy': 'partially_mapped_crossover',
    'mutation_strategy': 'inversion_mutation',
    'survival_selection_strategy': 'prob_survival',
}

setup93 = {
    'GENOME_SIZE': 8,
    'MAX_FITNESS_EVALUATIONS': 10000,
    'fitness_strategy': 'conflict_based',
    'termination_strategy': 'evaluation_count',
    'visualization_strategy': 'terminal',
    'metric_strategy': 'avg_similarity',
    'logging_strategy': 'logger',
    'print_type': 'csv_file',
    'POPULATION_SIZE': 182,
    'NUM_OFFSPRING_RATE': 0.458,
    'RECOMBINATION_RATE': 0.85,
    'MUTATION_RATE': 0.267,
    'TOURNAMENT_GROUP_SIZE': 0.454,
    'initialization_strategy': 'random_permutations',
    'parent_selection_strategy': 'tournament',
    'recombination_strategy': 'pmx_dp_rm',
    'mutation_strategy': 'swap_mutation',
    'survival_selection_strategy': 'prob_survival',
}

setup7 = {
    'GENOME_SIZE': 8,
    'MAX_FITNESS_EVALUATIONS': 10000,
    'fitness_strategy': 'conflict_based',
    'termination_strategy': 'evaluation_count',
    'visualization_strategy': 'terminal',
    'metric_strategy': 'avg_similarity',
    'logging_strategy': 'logger',
    'print_type': 'csv_file',
    'POPULATION_SIZE': 94,
    'NUM_OFFSPRING_RATE': 0.255,
    'RECOMBINATION_RATE': 0.651,
    'MUTATION_RATE': 0.494,
    'TOURNAMENT_GROUP_SIZE': 0.324,
    'initialization_strategy': 'random_permutations',
    'parent_selection_strategy': 'tournament',
    'recombination_strategy': 'pmx_dp_rm',
    'mutation_strategy': 'swap_mutation',
    'survival_selection_strategy': 'prob_survival',
}

setup100 = {
    'GENOME_SIZE': 8,
    'MAX_FITNESS_EVALUATIONS': 10000,
    'fitness_strategy': 'conflict_based',
    'termination_strategy': 'evaluation_count',
    'visualization_strategy': 'terminal',
    'metric_strategy': 'avg_similarity',
    'logging_strategy': 'logger',
    'print_type': 'csv_file',
    'POPULATION_SIZE': 127,
    'NUM_OFFSPRING_RATE': 0.454,
    'RECOMBINATION_RATE': 0.878,
    'MUTATION_RATE': 0.254,
    'TOURNAMENT_GROUP_SIZE': 0.472,
    'initialization_strategy': 'random_permutations',
    'parent_selection_strategy': 'tournament',
    'recombination_strategy': 'partially_mapped_crossover',
    'mutation_strategy': 'swap_mutation',
    'survival_selection_strategy': 'prob_survival',
}

setup61 = {
    'GENOME_SIZE': 8,
    'MAX_FITNESS_EVALUATIONS': 10000,
    'fitness_strategy': 'conflict_based',
    'termination_strategy': 'evaluation_count',
    'visualization_strategy': 'terminal',
    'metric_strategy': 'avg_similarity',
    'logging_strategy': 'logger',
    'print_type': 'csv_file',
    'POPULATION_SIZE': 131,
    'NUM_OFFSPRING_RATE': 0.36,
    'RECOMBINATION_RATE': 0.838,
    'MUTATION_RATE': 0.357,
    'TOURNAMENT_GROUP_SIZE': 0.54,
    'initialization_strategy': 'random_permutations',
    'parent_selection_strategy': 'tournament',
    'recombination_strategy': 'partially_mapped_crossover',
    'mutation_strategy': 'inversion_mutation',
    'survival_selection_strategy': 'prob_survival',
}

