setup53 = {
    'GENOME_SIZE': 7,
    'POPULATION_SIZE': 100,
    'MAX_FITNESS_EVALUATIONS': 10000,
    'fitness_strategy': 'conflict_based',
    'termination_strategy': 'evaluation_count',
    'visualization_strategy': 'terminal',
    'metric_strategy': 'avg_similarity',
    'logging_strategy': 'logger',
    'print_type': 'csv_file',
    'NUM_OFFSPRING_RATE': 0.381,
    'MUTATION_RATE': 0.306,
    'TOURNAMENT_GROUP_SIZE': 0.372,
    'initialization_strategy': ['random_permutations'],
    'parent_selection_strategy': ['tournament'],
    'recombination_strategy': ['partially_mapped_crossover'],
    'mutation_strategy': ['duplicate_replacement'],
    'survival_selection_strategy': ['prob_survival'],
    'POPULATION_SIZE': 188,
    'NUM_OFFSPRING_RATE': 0.405,
    'RECOMBINATION_RATE': 0.831,
    'MUTATION_RATE': 0.311,
    'TOURNAMENT_GROUP_SIZE': 0.46,
    'initialization_strategy': 'random_permutations',
    'parent_selection_strategy': 'tournament',
    'recombination_strategy': 'partially_mapped_crossover',
    'mutation_strategy': 'swap_mutation',
    'survival_selection_strategy': 'prob_survival',
}

setup36 = {
    'GENOME_SIZE': 7,
    'POPULATION_SIZE': 100,
    'MAX_FITNESS_EVALUATIONS': 10000,
    'fitness_strategy': 'conflict_based',
    'termination_strategy': 'evaluation_count',
    'visualization_strategy': 'terminal',
    'metric_strategy': 'avg_similarity',
    'logging_strategy': 'logger',
    'print_type': 'csv_file',
    'NUM_OFFSPRING_RATE': 0.381,
    'MUTATION_RATE': 0.306,
    'TOURNAMENT_GROUP_SIZE': 0.372,
    'initialization_strategy': ['random_permutations'],
    'parent_selection_strategy': ['tournament'],
    'recombination_strategy': ['partially_mapped_crossover'],
    'mutation_strategy': ['duplicate_replacement'],
    'survival_selection_strategy': ['prob_survival'],
    'POPULATION_SIZE': 194,
    'NUM_OFFSPRING_RATE': 0.328,
    'RECOMBINATION_RATE': 0.828,
    'MUTATION_RATE': 0.149,
    'TOURNAMENT_GROUP_SIZE': 0.665,
    'initialization_strategy': 'random_permutations',
    'parent_selection_strategy': 'tournament',
    'recombination_strategy': 'partially_mapped_crossover',
    'mutation_strategy': 'swap_mutation',
    'survival_selection_strategy': 'prob_survival',
}

setup8 = {
    'GENOME_SIZE': 7,
    'POPULATION_SIZE': 100,
    'MAX_FITNESS_EVALUATIONS': 10000,
    'fitness_strategy': 'conflict_based',
    'termination_strategy': 'evaluation_count',
    'visualization_strategy': 'terminal',
    'metric_strategy': 'avg_similarity',
    'logging_strategy': 'logger',
    'print_type': 'csv_file',
    'NUM_OFFSPRING_RATE': 0.381,
    'MUTATION_RATE': 0.306,
    'TOURNAMENT_GROUP_SIZE': 0.372,
    'initialization_strategy': ['random_permutations'],
    'parent_selection_strategy': ['tournament'],
    'recombination_strategy': ['partially_mapped_crossover'],
    'mutation_strategy': ['duplicate_replacement'],
    'survival_selection_strategy': ['prob_survival'],
    'POPULATION_SIZE': 186,
    'NUM_OFFSPRING_RATE': 0.455,
    'RECOMBINATION_RATE': 0.837,
    'MUTATION_RATE': 0.385,
    'TOURNAMENT_GROUP_SIZE': 0.194,
    'initialization_strategy': 'random_permutations',
    'parent_selection_strategy': 'tournament',
    'recombination_strategy': 'partially_mapped_crossover',
    'mutation_strategy': 'duplicate_replacement',
    'survival_selection_strategy': 'prob_survival',
}

setup70 = {
    'GENOME_SIZE': 7,
    'POPULATION_SIZE': 100,
    'MAX_FITNESS_EVALUATIONS': 10000,
    'fitness_strategy': 'conflict_based',
    'termination_strategy': 'evaluation_count',
    'visualization_strategy': 'terminal',
    'metric_strategy': 'avg_similarity',
    'logging_strategy': 'logger',
    'print_type': 'csv_file',
    'NUM_OFFSPRING_RATE': 0.381,
    'MUTATION_RATE': 0.306,
    'TOURNAMENT_GROUP_SIZE': 0.372,
    'initialization_strategy': ['random_permutations'],
    'parent_selection_strategy': ['tournament'],
    'recombination_strategy': ['partially_mapped_crossover'],
    'mutation_strategy': ['duplicate_replacement'],
    'survival_selection_strategy': ['prob_survival'],
    'POPULATION_SIZE': 165,
    'NUM_OFFSPRING_RATE': 0.327,
    'RECOMBINATION_RATE': 0.898,
    'MUTATION_RATE': 0.395,
    'TOURNAMENT_GROUP_SIZE': 0.333,
    'initialization_strategy': 'random_permutations',
    'parent_selection_strategy': 'tournament',
    'recombination_strategy': 'partially_mapped_crossover',
    'mutation_strategy': 'duplicate_replacement',
    'survival_selection_strategy': 'prob_survival',
}

setup48 = {
    'GENOME_SIZE': 7,
    'POPULATION_SIZE': 100,
    'MAX_FITNESS_EVALUATIONS': 10000,
    'fitness_strategy': 'conflict_based',
    'termination_strategy': 'evaluation_count',
    'visualization_strategy': 'terminal',
    'metric_strategy': 'avg_similarity',
    'logging_strategy': 'logger',
    'print_type': 'csv_file',
    'NUM_OFFSPRING_RATE': 0.381,
    'MUTATION_RATE': 0.306,
    'TOURNAMENT_GROUP_SIZE': 0.372,
    'initialization_strategy': ['random_permutations'],
    'parent_selection_strategy': ['tournament'],
    'recombination_strategy': ['partially_mapped_crossover'],
    'mutation_strategy': ['duplicate_replacement'],
    'survival_selection_strategy': ['prob_survival'],
    'POPULATION_SIZE': 184,
    'NUM_OFFSPRING_RATE': 0.459,
    'RECOMBINATION_RATE': 0.68,
    'MUTATION_RATE': 0.378,
    'TOURNAMENT_GROUP_SIZE': 0.139,
    'initialization_strategy': 'random_permutations',
    'parent_selection_strategy': 'tournament',
    'recombination_strategy': 'pmx_dp_rm',
    'mutation_strategy': 'inversion_mutation',
    'survival_selection_strategy': 'prob_survival',
}

setup18 = {
    'GENOME_SIZE': 7,
    'POPULATION_SIZE': 100,
    'MAX_FITNESS_EVALUATIONS': 10000,
    'fitness_strategy': 'conflict_based',
    'termination_strategy': 'evaluation_count',
    'visualization_strategy': 'terminal',
    'metric_strategy': 'avg_similarity',
    'logging_strategy': 'logger',
    'print_type': 'csv_file',
    'NUM_OFFSPRING_RATE': 0.381,
    'MUTATION_RATE': 0.306,
    'TOURNAMENT_GROUP_SIZE': 0.372,
    'initialization_strategy': ['random_permutations'],
    'parent_selection_strategy': ['tournament'],
    'recombination_strategy': ['partially_mapped_crossover'],
    'mutation_strategy': ['duplicate_replacement'],
    'survival_selection_strategy': ['prob_survival'],
    'POPULATION_SIZE': 74,
    'NUM_OFFSPRING_RATE': 0.369,
    'RECOMBINATION_RATE': 0.815,
    'MUTATION_RATE': 0.346,
    'TOURNAMENT_GROUP_SIZE': 0.416,
    'initialization_strategy': 'random_permutations',
    'parent_selection_strategy': 'tournament',
    'recombination_strategy': 'pmx_dp_rm',
    'mutation_strategy': 'duplicate_replacement',
    'survival_selection_strategy': 'prob_survival',
}

setup44 = {
    'GENOME_SIZE': 7,
    'POPULATION_SIZE': 100,
    'MAX_FITNESS_EVALUATIONS': 10000,
    'fitness_strategy': 'conflict_based',
    'termination_strategy': 'evaluation_count',
    'visualization_strategy': 'terminal',
    'metric_strategy': 'avg_similarity',
    'logging_strategy': 'logger',
    'print_type': 'csv_file',
    'NUM_OFFSPRING_RATE': 0.381,
    'MUTATION_RATE': 0.306,
    'TOURNAMENT_GROUP_SIZE': 0.372,
    'initialization_strategy': ['random_permutations'],
    'parent_selection_strategy': ['tournament'],
    'recombination_strategy': ['partially_mapped_crossover'],
    'mutation_strategy': ['duplicate_replacement'],
    'survival_selection_strategy': ['prob_survival'],
    'POPULATION_SIZE': 133,
    'NUM_OFFSPRING_RATE': 0.194,
    'RECOMBINATION_RATE': 0.688,
    'MUTATION_RATE': 0.412,
    'TOURNAMENT_GROUP_SIZE': 0.473,
    'initialization_strategy': 'random_permutations',
    'parent_selection_strategy': 'tournament',
    'recombination_strategy': 'pmx_dp_rm',
    'mutation_strategy': 'duplicate_replacement',
    'survival_selection_strategy': 'prob_survival',
}

setup27 = {
    'GENOME_SIZE': 7,
    'POPULATION_SIZE': 100,
    'MAX_FITNESS_EVALUATIONS': 10000,
    'fitness_strategy': 'conflict_based',
    'termination_strategy': 'evaluation_count',
    'visualization_strategy': 'terminal',
    'metric_strategy': 'avg_similarity',
    'logging_strategy': 'logger',
    'print_type': 'csv_file',
    'NUM_OFFSPRING_RATE': 0.381,
    'MUTATION_RATE': 0.306,
    'TOURNAMENT_GROUP_SIZE': 0.372,
    'initialization_strategy': ['random_permutations'],
    'parent_selection_strategy': ['tournament'],
    'recombination_strategy': ['partially_mapped_crossover'],
    'mutation_strategy': ['duplicate_replacement'],
    'survival_selection_strategy': ['prob_survival'],
    'POPULATION_SIZE': 85,
    'NUM_OFFSPRING_RATE': 0.415,
    'RECOMBINATION_RATE': 0.614,
    'MUTATION_RATE': 0.159,
    'TOURNAMENT_GROUP_SIZE': 0.262,
    'initialization_strategy': 'random_permutations',
    'parent_selection_strategy': 'tournament',
    'recombination_strategy': 'pmx_dp_rm',
    'mutation_strategy': 'duplicate_replacement',
    'survival_selection_strategy': 'prob_survival',
}

setup67 = {
    'GENOME_SIZE': 7,
    'POPULATION_SIZE': 100,
    'MAX_FITNESS_EVALUATIONS': 10000,
    'fitness_strategy': 'conflict_based',
    'termination_strategy': 'evaluation_count',
    'visualization_strategy': 'terminal',
    'metric_strategy': 'avg_similarity',
    'logging_strategy': 'logger',
    'print_type': 'csv_file',
    'NUM_OFFSPRING_RATE': 0.381,
    'MUTATION_RATE': 0.306,
    'TOURNAMENT_GROUP_SIZE': 0.372,
    'initialization_strategy': ['random_permutations'],
    'parent_selection_strategy': ['tournament'],
    'recombination_strategy': ['partially_mapped_crossover'],
    'mutation_strategy': ['duplicate_replacement'],
    'survival_selection_strategy': ['prob_survival'],
    'POPULATION_SIZE': 161,
    'NUM_OFFSPRING_RATE': 0.482,
    'RECOMBINATION_RATE': 0.703,
    'MUTATION_RATE': 0.027,
    'TOURNAMENT_GROUP_SIZE': 0.657,
    'initialization_strategy': 'random_permutations',
    'parent_selection_strategy': 'tournament',
    'recombination_strategy': 'pmx_dp_rm',
    'mutation_strategy': 'duplicate_replacement',
    'survival_selection_strategy': 'prob_survival',
}

setup4 = {
    'GENOME_SIZE': 7,
    'POPULATION_SIZE': 100,
    'MAX_FITNESS_EVALUATIONS': 10000,
    'fitness_strategy': 'conflict_based',
    'termination_strategy': 'evaluation_count',
    'visualization_strategy': 'terminal',
    'metric_strategy': 'avg_similarity',
    'logging_strategy': 'logger',
    'print_type': 'csv_file',
    'NUM_OFFSPRING_RATE': 0.381,
    'MUTATION_RATE': 0.306,
    'TOURNAMENT_GROUP_SIZE': 0.372,
    'initialization_strategy': ['random_permutations'],
    'parent_selection_strategy': ['tournament'],
    'recombination_strategy': ['partially_mapped_crossover'],
    'mutation_strategy': ['duplicate_replacement'],
    'survival_selection_strategy': ['prob_survival'],
    'POPULATION_SIZE': 177,
    'NUM_OFFSPRING_RATE': 0.486,
    'RECOMBINATION_RATE': 0.602,
    'MUTATION_RATE': 0.089,
    'TOURNAMENT_GROUP_SIZE': 0.299,
    'initialization_strategy': 'random_permutations',
    'parent_selection_strategy': 'tournament',
    'recombination_strategy': 'pmx_dp_rm',
    'mutation_strategy': 'duplicate_replacement',
    'survival_selection_strategy': 'prob_survival',
}

